Lab09: main.o
	g++ -g -std=c++11 -Wall main.o -o Lab09

main.o: main.cpp bubbleSort.cpp insertionSort.cpp mergesort.cpp quicksort.cpp selectionSort.cpp
	g++ -g -std=c++11 -Wall -c main.cpp bubbleSort.cpp insertionSort.cpp mergesort.cpp quicksort.cpp selectionSort.cpp

clean:
	rm *.o Lab09
